package com.aws.dynamodb.crud.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Employee")
@Data
@AllArgsConstructor
@NoArgsConstructor
public class Employee {

	/**
	 * Important annotation to make this field as primary key (hashKey) for DynamoDB
	 * table
	 */

	@DynamoDBHashKey(attributeName = "empId")
	private String empId;
	private String empName;
	private String address;

}
